import{i as n,a as g,S as y}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const l=document.querySelector(".gallery"),h=document.querySelector(".form"),b="50762825-7fe49127b3d94f6c93c99dfe1",L="photo";h.addEventListener("submit",$);function $(a){a.preventDefault();const r=a.target.elements["search-text"].value.trim();if(l.innerHTML="",r===""){n.info({message:"Будь ласка, введіть щось для пошуку.",position:"topRight"});return}g.get("https://pixabay.com/api/",{params:{key:b,q:r,image_type:L,orientation:"horizontal",safesearch:!0}}).then(o=>{const i=o.data.hits;if(i.length===0){n.info({message:"На жаль, за вашим запитом не знайдено зображень. Спробуйте ще раз!",position:"topRight"});return}const e=i.map(({webformatURL:s,largeImageURL:c,tags:f,likes:m,views:p,comments:u,downloads:d})=>`
                <li class="gallery-item">
                    <a class="gallery-link" href="${c}">
                        <img class="gallery-image" src="${s}" alt="${f}" />
                    </a>
                    <div class="info">
                        <p class="info-item"> <b>Likes:</b> ${m} <b>Views:</b> ${p} <b>Comments:</b> ${u} <b>Downloads:</b> ${d}</p>
                    </div>
                </li>
            `).join("");l.innerHTML=e,new y(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),n.success({message:`Знайдено ${o.data.totalHits} зображень за вашим запитом.`,position:"topRight"})}).catch(o=>{console.error("Помилка запиту до Pixabay API:",o),n.error({message:"Не вдалося отримати зображення. Будь ласка, спробуйте пізніше.",position:"topRight"})}).finally(()=>{a.target.reset()})}
//# sourceMappingURL=index.js.map
